// Add an include for each primitive
#include "primitives/primitive.h"
#include "primitives/plane-primitive.h"
#include "primitives/sphere-primitive.h"
#include "primitives/union-primitive.h"
#include "primitives/decorator-primitive.h"
#include "primitives/transformer-primitive.h"
#include "primitives/csg-union-primitive.h"
#include "primitives/rectangle-primitive.h"
#include "primitives/box-primitive.h"
#include "primitives/triangle-primitive.h"
#include "primitives/cylinder-primitive.h"
#include "primitives/disk-primitive.h"
#include "primitives/bbacc.h"
#include "primitives/mesh/mesh-primitive.h"
#include "primitives/resizer-primitive.h"
#include "primitives/cone-primitive.h"